/**
 * Vision-RCP AuthGate — Login screen with secret key input.
 */

import { useState, type FormEvent } from 'react';
import './AuthGate.css';

interface AuthGateProps {
  onLogin: (secret: string) => Promise<void>;
  error?: string;
  mode?: 'local' | 'remote';
  sessionId?: string;
  isAuthenticating?: boolean;
}

export function AuthGate({ onLogin, error, mode = 'local', sessionId, isAuthenticating }: AuthGateProps) {
  const [secret, setSecret] = useState('');
  const [loading, setLoading] = useState(false);
  const [localError, setLocalError] = useState('');

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!secret.trim()) return;

    setLoading(true);
    setLocalError('');

    try {
      await onLogin(secret.trim());
    } catch (err) {
      setLocalError(err instanceof Error ? err.message : 'Authentication failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-gate">
      <div className="auth-gate__card">
        <div className="auth-gate__logo">
          <div className="auth-gate__icon">⬡</div>
          <h1 className="auth-gate__title">VISION-RCP</h1>
          <p className="auth-gate__subtitle">
            {mode === 'remote' ? `Remote Session: ${sessionId}` : 'Local Agent Control Plane'}
          </p>
        </div>

        {isAuthenticating ? (
          <div className="auth-gate__loading">
            <span className="auth-gate__spinner" />
            <p>One-Click Handshake...</p>
            <p className="auth-gate__subtext">Verifying link secret with daemon...</p>
          </div>
        ) : (
          <form className="auth-gate__form" onSubmit={handleSubmit}>
            <div className="auth-gate__field">
              <label className="auth-gate__label" htmlFor="secret-input">
                Secret Key
              </label>
              <input
                id="secret-input"
                className="auth-gate__input mono"
                type="password"
                value={secret}
                onChange={(e) => setSecret(e.target.value)}
                placeholder="Paste your daemon secret key..."
                autoFocus
                autoComplete="off"
                spellCheck={false}
                disabled={loading}
              />
            </div>

            {(error || localError) && (
              <div className="auth-gate__error">
                {error || localError}
              </div>
            )}

            <button
              className="auth-gate__submit"
              type="submit"
              disabled={loading || !secret.trim()}
            >
              {loading ? (
                <span className="auth-gate__spinner" />
              ) : (
                mode === 'remote' ? 'Join & Authenticate' : 'Authenticate'
              )}
            </button>
          </form>
        )}

        <p className="auth-gate__hint">
          {mode === 'remote' 
            ? 'Enter the secret key generated by the daemon hosting this session.'
            : 'The secret key is displayed in the daemon terminal on first launch.'}
        </p>
      </div>
    </div>
  );
}
